test_that("Funkcja strategia_nowa przyjmuje jeden argument i zwraca wektor dlugosci 7",{
  stado <- c(1,1,1,3,1,0,0)
  names(stado) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  expect_error(strategia_nowa())
  expect_is(strategia_nowa(stado),"numeric")
  expect_length(strategia_nowa(stado),7)
})
test_that("Funcja daje poprawne wartosci",{
  stado1 <- c(1,1,1,2,1,0,0)
  names(stado1) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  expect_equivalent(strategia_nowa(stado1),c(1,1,1,0,2,0,0))
  stado2 <- c(1,4,1,1,0,0,0)
  names(stado2) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  expect_equivalent(strategia_nowa(stado2),c(1,0,0,0,1,0,0))
})
