test_that("Wymiana jedno na kilka przyjmuje cztery argumenty i zwraca wektor dlugosci 7",{
  stado <- c(1,1,1,1,1,0,0)
  names(stado) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  wartosc_w_krolikach <- c(1,6,12,36,72,6,36)
  names(wartosc_w_krolikach) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  expect_error(.jedno_na_kilka())
  expect_error(.jedno_na_kilka(stado))
  expect_error(.jedno_na_kilka(wartosc_w_krolikach,"krolik"))
  expect_is(.jedno_na_kilka(wartosc_w_krolikach,stado,"krowa","owca"),"numeric")
  expect_length(.jedno_na_kilka(wartosc_w_krolikach,stado,"krowa","owca"),7)
  expect_true(is.logical(.jedno_na_kilka(wartosc_w_krolikach,stado,"owca","krowa")))
})
test_that("Wymiana daje poprawne wyniki",{
  stado <- c(1,1,1,1,1,0,0)
  names(stado) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  wartosc_w_krolikach <- c(1,6,12,36,72,6,36)
  names(wartosc_w_krolikach) <- c("krolik","owca","swinia","krowa","kon","maly_pies","duzy_pies")
  expect_equivalent(.jedno_na_kilka(wartosc_w_krolikach,stado,"krowa","owca"),c(0,6,0,-1,0,0,0))
})
